# Pandas

NumPy creates ndarrays that must contain values that are of the same data type.

Pandas creates dataframes. Each column in a dataframe is an ndarray. This allows us to have traditional tables of data where each column can be a different data type.

In [1]:
import numpy as np
import pandas as pd

The basic data structure in pandas is the *series*. You can construct it in a similar fashion to making a numpy array.

The command to make a Series object is

`pd.Series(data, index=index)`

the `index` argument is optional

In [2]:
data = pd.Series([0.25, 0.5, 0.75, 1.0])
print(data)
print(type(data))

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64
<class 'pandas.core.series.Series'>


In [3]:
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

The series is printed out in a table form.

The type is a Pandas Series

In [4]:
print(data.values)
print(type(data.values))

[0.25 0.5  0.75 1.  ]
<class 'numpy.ndarray'>


The values attribute of the series is a numpy array.

In [5]:
print(data.index)
print(type(data.index))  # the row names are known as the index

RangeIndex(start=0, stop=4, step=1)
<class 'pandas.core.indexes.range.RangeIndex'>


You can subset a pandas series like other python objects

In [6]:
print(data[1])
print(type(data[1]))  # when you select only one value, it simplifies the object

0.5
<class 'numpy.float64'>


In [7]:
print(data[1:3])
print(type(data[1:3]))  # selecting multiple values returns a series

1    0.50
2    0.75
dtype: float64
<class 'pandas.core.series.Series'>


In [8]:
print(data[np.array([1,0,2])])  # fancy indexing using a numpy array

1    0.50
0    0.25
2    0.75
dtype: float64


In [9]:
# specifying the index values
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index=['a', 'b', 'c', 'd'])
print(data)

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64


In [12]:
data.values

array([0.25, 0.5 , 0.75, 1.  ])

In [13]:
data.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [14]:
data[1]  # subset with index position

0.5

In [15]:
data["a"]  # subset with index names

0.25

In [16]:
data[0:2]  # slicing behavior is unchanged

a    0.25
b    0.50
dtype: float64

In [17]:
data["a":"c"] # using names includes the last value

a    0.25
b    0.50
c    0.75
dtype: float64

In [18]:
# creating a series from a python dictionary
# remember, dictionary construction uses curly braces {}
samp_dict = {'Archie': 71,
             'Betty': 66,
             'Veronica': 62,
             'Jughead': 72,
             'Cheryl': 66}
samp_series = pd.Series(samp_dict)
samp_series # the series gets alphabetized by its index

Archie      71
Betty       66
Veronica    62
Jughead     72
Cheryl      66
dtype: int64

In [19]:
print(samp_series.index)

Index(['Archie', 'Betty', 'Veronica', 'Jughead', 'Cheryl'], dtype='object')


In [20]:
samp_series.values

array([71, 66, 62, 72, 66], dtype=int64)

In [21]:
print(type(samp_dict))
print(type(samp_series))

<class 'dict'>
<class 'pandas.core.series.Series'>


In [22]:
actor_dict = {'Archie': "KJ",
              'Jughead': "Cole",
              'Betty': "Lili",
              'Veronica': "Camila",
              'Cheryl': "Madelaine"}  # note that the dictionary order is not same here
actor = pd.Series(actor_dict)  # still get alphabetized by index
print(actor)

Archie             KJ
Jughead          Cole
Betty            Lili
Veronica       Camila
Cheryl      Madelaine
dtype: object


# Creating a DataFrame

In [24]:
# we create a dataframe by providing a dictionary of series objects
# the dictionary key becomes the column name
# the dictionary values become values
# the keys within the dictionaries become the indices 
riverdale = pd.DataFrame({'height': samp_series,
                       'actor': actor})  

# the DataFrame will match the indices and sort them
print(riverdale)

          height      actor
Archie        71         KJ
Betty         66       Lili
Cheryl        66  Madelaine
Jughead       72       Cole
Veronica      62     Camila


In [25]:
print(type(riverdale))  # this is a DataFrame object

<class 'pandas.core.frame.DataFrame'>


In [26]:
data = [{'a': 0, 'b': 0}, {'a': 1, 'b': 2}, {'a': 2, 'b': 5}]  # data is a list of dictionaries
# each dictionary needs to have the same set of keys
data

[{'a': 0, 'b': 0}, {'a': 1, 'b': 2}, {'a': 2, 'b': 5}]

In [27]:
print(pd.DataFrame(data, index = [1,2,3]))

   a  b
1  0  0
2  1  2
3  2  5


In [28]:
data2 = [{'a': 0, 'b': 0}, {'a': 1, 'b': 2}, {'a': 2, 'c': 5}]  # data is a list of dictionaries
# each dictionary needs to have the same set of keys, otherwise, NAs will appear
data2

[{'a': 0, 'b': 0}, {'a': 1, 'b': 2}, {'a': 2, 'c': 5}]

In [30]:
pd.DataFrame(data2)  # if the index argument is not supplied, it defaults to integer index start at 0

a    b    c
0  0  0.0  NaN
1  1  2.0  NaN
2  2  NaN  5.0

In [31]:
data3 = {'a' : [1,2,3], 'b': ['x','y','z']} 
# data3 is a dictionary. the keys form column names, and the values are lists of values
data3

{'a': [1, 2, 3], 'b': ['x', 'y', 'z']}

In [32]:
pd.DataFrame(data3)

a  b
0  1  x
1  2  y
2  3  z

In [33]:
data = np.random.randint(10, size = 10).reshape([5,2])
print(data)

[[1 1]
 [9 3]
 [3 8]
 [9 5]
 [1 1]]


In [34]:
print(pd.DataFrame(data, columns = ["x","y"], index = ['a','b','c','d','e']))

   x  y
a  1  1
b  9  3
c  3  8
d  9  5
e  1  1


# Subsetting the DataFrame

In [ ]:
print(riverdale)

In [ ]:
print(riverdale.keys())

In [ ]:
riverdale['actor']  # extracting the column

In [ ]:
riverdale.actor

In [ ]:
riverdale.actor[1]

In [ ]:
riverdale.actor['Jughead']

In [ ]:
print(riverdale.T)  # prints a copy of the transpose

In [ ]:
print(riverdale.loc['Jughead']) # subset based on location to get a row
print(type(riverdale.loc['Jughead']))
print(type(riverdale.loc['Jughead'].values))  # the values are of mixed type but is still a numpy array. 
# this is possible because it is a structured numpy array. (covered in "Python for Data Science" chapter 2)

In [ ]:
print(riverdale.loc[:,'height']) # subset based on location to get a column
print(type(riverdale.loc[:,'height']))  #the object is a pandas series
print(type(riverdale.loc[:,'height'].values))

In [ ]:
riverdale.loc['Archie','height']  # you can provide a pair of 'coordinates' to get a particular value

In [ ]:
riverdale.iloc[3,] # subset based on index location

In [ ]:
riverdale.iloc[0, 1] # pair of coordinates

# Importing Data with pd.read_csv()

In [ ]:
url = 'https://assets.datacamp.com/production/course_1607/datasets/titanic_sub.csv'
titanic = pd.read_csv(url)

In [ ]:
titanic.head()

In [ ]:
titanic.shape

In [ ]:
titanic.columns

In [ ]:
titanic.info()

In [ ]:
titanic.describe()  # displays summary statistics of the numeric variables